### ISSUE TITLE
Remove individual CV-001-MTR

### ISSUE THREAD

**Issue by mhodki** [uwasystemhealth/Paper_Archive_Maintenance_Activity#1]
I have added 2 individuals, one is correct CV001-MTR and the other is not CV-001-MTR
When I try and delere CV-001-MTR in the functional breakdown conveyor.owl file. It won't let me.

**Comment by mattys101** [comment]
This is not relevant anymore as the new example is for the centrifiugal pump. This may become a problem again if we dig the conveyor example out of the version history though.
